### ISSUE TITLE
uso de oauth scopes 

### ISSUE THREAD

**Issue by PMARZV** [Blad3Mak3r/Kotify#5]
tengo una pregunta. Cuando usas Kotify para pedir la playlist Top Global 50, se hace uso de los Oauth scopes o ni? Lo digo porque he pedido una extensión de la cuota de usuarios a la API de spotify y me dice que pueden haber mas de 1 Oauth Scopes en uso. Te dejo el codigo que uso.

```kt
val kotify = Kotify(
    clientID = "CLIENTID",
    clientSecret = "CLIENT SECRET"
)

val playlist: List<PlaylistPagination.Item> =
    kotify.playlists.get("37i9dQZEVXbMDoHDwVN2tF").tracks.items



val tracks: ArrayList<Track> = playlist.map { it.track } as ArrayList<Track>

for (i in 0 until tracks.count()) {


    val SEVERALartistsname: ArrayList<Artist> =
        tracks[i].artists as ArrayList<Artist>
    for (o in 0 until SEVERALartistsname.count()) {
        if (artistname == null) {
            artistname = SEVERALartistsname[o].name
        } else {
            artistname = artistname + ", " + SEVERALartistsname[o].name
        }
    }


    val SEVERALalbumimg: ArrayList<Image> =
        tracks[i].album?.images as ArrayList<Image>
    val artworkTrack = SEVERALalbumimg[2].url


    val songname = tracks[i].name ?: "N/A"
    val nameartist = songname + System.lineSeparator() + artistname


    courseList2.add(namespoty(i + 1, nameartist, artworkTrack))
    SEVERALartistsname.clear()
    artistname = null


}
```

**Comment by Blad3Mak3r** [comment]
Los scopes son definidos por la [API de Spotify](https://developer.spotify.com/documentation/general/guides/authorization/scopes/), ninguna petición por si sola hace uso de scopes, hay algunos endpoints que si requieren de OAuth scopes ya que acceden a datos que requieren una autorización y un nivel de permiso requerido (scopes).
De todas formas te pongo uno ejemplos de la funcionalidad de Kotify.

Cuando es una petición que no requiere de autentificación por parte del usuario solo se usa las credenciales [Client Credentials Flow](https://developer.spotify.com/documentation/general/guides/authorization/client-credentials/) que no requiren ningún scope ni autorización por parte del usuario.

Cuando una petición requiere de un accessToken o es encapsulada dentro de una función [withAccessToken()](https://github.com/Blad3Mak3r/Kotify/blob/main/src/main/kotlin/tv/blademaker/kotify/utils/KUtils.kt) ([ejemplo](https://github.com/Blad3Mak3r/Kotify/blob/main/src/main/kotlin/tv/blademaker/kotify/services/TracksService.kt#L42-L46)) se usará ese token para hacer la petición, en caso de que ese token no tenga el scope [`` user-library-modify ``](https://developer.spotify.com/documentation/general/guides/authorization/scopes/#user-library-modify) la API de Spotify devolverá un error 403, informando de que tienes acceso a la API pero no a este recurso.

En cada request Kotify comprueba si ha sido añadido algún token al contexto de la corrutina y en caso de que no usará las credenciales de la aplicación:
https://github.com/Blad3Mak3r/Kotify/blob/main/src/main/kotlin/tv/blademaker/kotify/request/Request.kt#L57-L58
